### ISSUE TITLE
formatting on slide 12 (on Chrome)

### ISSUE THREAD

**Issue by trjaffe** [nasa-gcn/gcn-presentation#4]
... doesn't look right on Chrome, though it does in Safari:
<img width="512" alt="Screen Shot 2022-07-21 at 09 29 45" src="https://user-images.githubusercontent.com/20912165/180225631-cac60d46-8819-4925-ac4e-acaa0ba36377.png">

**Comment by dakota002** [comment]
https://github.com/nasa-gcn/gcn-presentation/pull/5

**Comment by lpsinger** [comment]
Fixed by #5.

**Comment by lpsinger** [comment]
I think that this was fixed too in #5. Was it?

**Comment by dakota002** [comment]
Yep, included both. The github svg pulled at 250x250 for some reason where the others were much smaller. I defined a size in both instances and it seems to have done the job

**Comment by trjaffe** [comment]
I cannot confirm until it's redeployed, but I believe Dakota.

**Comment by lpsinger** [comment]
It should be redeployed by now. Did you refresh?

**Comment by trjaffe** [comment]
Yes, looks good now.
