### ISSUE TITLE
ADASS presentation additions

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn-presentation#9]
What makes GCN special from a tech perspective?
- kafka, innovative things compared to Rubin & SCiMMA
	- kafka is already used throughout NASA, and we’re supporting FedRAMP thru confluent so we can pay someone else to manage our kafka cluster
	- OpenID Connect to keep our authentication and authorization decoupled from kafka broker
	- unmodified stock kafka broker - don’t need to side load any of our code
		- much less backend software to maintain
		- works with self-managed kafka broker or by confluent or amazon (vendor neutral) -> standards-based approach
- NASA is heavy user of Kafka (so is LIGO)
	- LIGO transitioning to SciTokens (based on OpenID Connect), allows delegation of access to high-performance computing workflows
- EC2 -> Kubernetes -> Confluent Cloud

Website is innovative
- USWDS - used by most federal agencies - emphasis on accessibility
	- NASAWDS - NASA customization of USWDS, we’ve contributed patches upstream
- 100% typescript - modern way to build web apps - single codebase for server and client side
	- compared to many astro apps that use flask and django
- open source website - issues + feedback
- continuously deployed with GitHub actions
- hosted on AWS Lambda - scales effortlessly
- early adopters of Remix - contribute regularly
- Architect - infrastructure as code tool for server less deployments on AWS - we contribute to that

**Comment by lpsinger** [comment]
Here's the graphic for the web site tech stack slide.

![gcn-web-site-tech-stack](https://user-images.githubusercontent.com/728407/198688179-18cfda1e-ec01-419d-8104-a2cf31446efd.svg)
